# Generated by Django 2.2 on 2022-02-18 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_taskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
