# Generated by Django 2.2 on 2022-02-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_profilefeeditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='profileImages'),
            preserve_default=False,
        ),
    ]
